### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by MD-Uchuu-Keiji-Nova** [idleberg/atom-build-sass#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [build-sass](https://github.com/idleberg/atom-build-sass) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of null

```
At C:\Users\Proyectos\.atom\packages\build-sass\lib\provider.js:99

TypeError: Cannot read property 'toString' of null
    at SassProvider.isEligible (/packages/build-sass/lib/provider.js:99:23)
    at /packages/build/lib/target-manager.js:68:30
    at Array.filter (<anonymous>)
    at /packages/build/lib/target-manager.js:68:10
    at Array.map (<anonymous>)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:58:39)
    at /packages/build/lib/target-manager.js:18:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1202691)
    at Project.addPath (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:411240)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:951002)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
  4x -9:17.2.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
  2x -9:04.1.0 application:reopen-project (input.hidden-input)
  2x -7:55.4.0 core:close (input.hidden-input)
     -7:33.7.0 application:reopen-project (atom-workspace.workspace.scrollbars-visible-always.theme-megumin-syntax.theme-kecleon-ui)
     -4:13.7.0 github:open-reviews-tab (atom-pane.pane.active)
     -4:08.4.0 tree-view:toggle (atom-pane.pane.active)
     -3:57.1.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:35.4.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:31.6.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:24 application:reopen-project (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
90s-hack-syntax 0.3.0 
atom-python-run 0.9.7 
atom-sun-glass-syntax 1.0.5 
build 0.70.0 
build-sass 0.11.0 
busy-signal 2.0.1 
Hydrogen 2.14.1 
intentions 1.1.5 
kecleon-ui 0.1.1 
linter 2.3.1 
linter-ui-default 1.8.1 
megumin-syntax 0.1.0 
script 3.26.0 
```

**Comment by idleberg** [comment]
Did you install `sass` and is it exposed in your `PATH` environment variable?
